version: '3.1'

services:

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: squadMakersUsername
      MONGO_INITDB_ROOT_PASSWORD: squadMakersPassword
      MONGO_INITDB_DATABASE: squadMakersDatabase

  back:
    build: .
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - mongo
